# Generated by Django 3.2.18 on 2023-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_chat_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('latin', 'latin'), ('cyrill', 'cyrill')], default='cyrill', max_length=100),
        ),
    ]
