# Generated by Django 3.2.18 on 2023-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
