# Generated by Django 3.2.16 on 2023-02-23 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(choices=[('Dollar', 'dollar'), ('Som', 'som')], max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default='15:28:18')),
                ('body', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('location', models.URLField(null=True)),
                ('image', models.FileField(null=True, upload_to='photos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])])),
                ('images', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('inactive', 'inactive'), ('rejected', 'rejected'), ('published', 'published')], default='inactive', max_length=255)),
                ('notisification', models.CharField(blank=True, max_length=255, null=True)),
                ('viewers', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('user_controller', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CreateCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('icon', models.FileField(blank=True, upload_to='photos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='NotisificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_sended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParamSelectValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.createcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_value', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('select', 'select'), ('multiselect', 'multiselect')], max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(blank=True, max_length=255, null=True)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='product.announcementmodel')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryparams')),
                ('selecttion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paramselectvalues')),
            ],
        ),
        migrations.AddField(
            model_name='paramselectvalues',
            name='parent_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.subcategoryparams'),
        ),
    ]
