# Generated by Django 3.2.16 on 2023-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='time',
            field=models.TimeField(default='15:49:27'),
        ),
    ]
