# Generated by Django 3.2.16 on 2023-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_announcementmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='time',
            field=models.TimeField(default='19:29:03'),
        ),
    ]
