# Generated by Django 3.2.18 on 2023-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_announcementmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
