# Generated by Django 3.2.18 on 2023-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_announcementmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='kelishuv',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
