# Generated by Django 3.2.18 on 2023-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_announcementmodel_kelishuv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
