# Generated by Django 3.2.18 on 2023-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_announcementmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
